apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rocketmqConsole.name }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: {{ .Values.rocketmqConsole.progressDeadlineSeconds }}
  replicas: {{ .Values.rocketmqConsole.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rocketmq-console
  strategy:
    rollingUpdate:
{{- with .Values.rocketmqConsole.rollingUpdate }}
{{ toYaml . | indent 6 }}
{{- end }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rocketmq-console
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: "{{ .Values.rocketmqConsole.javaOpts }}"
        image: {{ .Values.rocketmqConsole.consoleImageName }}:{{ .Values.rocketmqConsole.consoleImageTag }}
        imagePullPolicy: {{ .Values.rocketmqConsole.imagePullPolicy }}
        name: {{ .Values.rocketmqConsole.name }}
        ports:
        - containerPort: {{ .Values.rocketmqConsole.containerPort }}
          protocol: TCP
        resources:
{{- with .Values.rocketmqConsole.resources }}
{{ toYaml . | indent 10 }}
{{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
