---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rocketmqConsole.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: rocketmq-console
spec:
  type: {{ .Values.rocketmqConsole.networkType }}
  selector:
    app: rocketmq-console
  ports:
    - port: {{ .Values.rocketmqConsole.clusterPort }}
      targetPort: {{ .Values.rocketmqConsole.containerPort }}
      protocol: TCP
{{- if .Values.rocketmqConsole.nodePort }}
      nodePort: {{ .Values.rocketmqConsole.nodePort }}
{{- end }}

