---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rocketmqNameserver.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.rocketmqNameserver.networkType }}
  selector:
    name_service_cr: {{ .Values.rocketmqNameserver.name }}
  ports:
    - port: {{ .Values.rocketmqNameserver.clusterPort }}
      targetPort: 9876
      # use this port to access the name server cluster
{{- if .Values.rocketmqNameserver.nodePort }}
      nodePort: {{ .Values.rocketmqNameserver.nodePort }}
{{- end }}