apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.rocketmqBrokerA.name }}
  namespace: {{ .Release.Namespace }}
spec:
  podManagementPolicy: OrderedReady
  replicas: {{ .Values.rocketmqBrokerA.replicaPerGroup }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rocketmq-broker
      broker_cr: {{ .Values.rocketmqBrokerA.name }}
  serviceName: ""
  template:
    metadata:
      labels:
        app: rocketmq-broker
        broker_cr: {{ .Values.rocketmqBrokerA.name }}
    spec:
      containers:
      - env:
        - name: NAMESRV_ADDR
          value: {{ .Values.rocketmqBrokerA.nameServerAddr | quote }}
        - name: BROKER_CLUSTER_NAME
          value: {{ .Values.rocketmqBrokerA.clusterName | quote }}
        - name: BROKER_MEM
          valueFrom:
            configMapKeyRef:
              key: BROKER_MEM
              name: broker-config
        image: {{ .Values.rocketmqBrokerA.imageName }}:{{ .Values.rocketmqBrokerA.imageTag }}
        command:
        - /bin/bash
        - "-c"
        - |
          set -ex
          # 从Pod的序号，生成BROKER_ID
          [[ $(hostname) =~ -([0-9]+)$ ]] || exit 1
          export BROKER_ID=${BASH_REMATCH[1]}
          export BROKER_NAME="{{ .Values.rocketmqBrokerA.name }}-${BROKER_ID}"
          ./brokerStart.sh
        imagePullPolicy: {{ .Values.rocketmqBrokerA.imagePullPolicy }}
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/bash
              - -c
              - echo Initial broker
        name: broker
        ports:
        - containerPort: 10909
          name: vip
          protocol: TCP
        - containerPort: 10911
          name: main
          protocol: TCP
        - containerPort: 10912
          name: ha
          protocol: TCP
        resources:
{{- with .Values.rocketmqBrokerA.resources }}
{{ toYaml . | indent 10 }}
{{- end }}
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /root/logs
          name: broker-storage
          subPath: logs/broker-0-master
        - mountPath: /root/store
          name: broker-storage
          subPath: store/broker-0-master
        - mountPath: /root/rocketmq/broker/conf/broker-common.conf
          name: broker-config
          subPath: broker-common.conf
      dnsPolicy: {{ .Values.rocketmqBrokerA.dnsPolicy }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: {{ .Values.rocketmqBrokerA.terminationGracePeriodSeconds }}
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: broker-common.conf
            path: broker-common.conf
          name: {{ .Values.brokerConfigMap.name }}
        name: broker-config
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolumeClaim
{{- with .Values.rocketmqBrokerA.volumeClaimTemplates }}
{{ toYaml . | indent 4 }}
{{- end }}
      volumeMode: Filesystem
