{{- if .Values.rocketmqConsole.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rocketmqConsole.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: rocketmq-console
spec:
  type: {{ .Values.rocketmqConsole.networkType }}
  selector:
    app: rocketmq-console
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
{{- if (and (eq .Values.rocketmqConsole.networkType "NodePort") (not (empty .Values.rocketmqConsole.nodePort))) }}
      nodePort: {{ .Values.rocketmqConsole.nodePort }}
{{- end }}
{{- end }}
