---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: rocketmq
    component: rocketmq
    middleware: rocketmq
  name: {{ .Values.rocketmqNameserver.name }}-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: name-server
    port: 9876
    protocol: TCP
    targetPort: 9876
  publishNotReadyAddresses: true
  selector:
    name_service_cr: rocketmq-name-server
  sessionAffinity: None
  type: ClusterIP
