{{- if .Values.rocketmqExporter.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/instance: {{ .Values.rocketmqExporter.name }}
    app.kubernetes.io/name: {{ .Values.rocketmqExporter.name }}
  name: {{ .Values.rocketmqExporter.name }}
  namespace: {{ .Release.Namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.rocketmqExporter.name }}
      app.kubernetes.io/name: {{ .Values.rocketmqExporter.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "5557"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/instance: {{ .Values.rocketmqExporter.name }}
        app.kubernetes.io/name: {{ .Values.rocketmqExporter.name }}
    spec:
      containers:
      - env:
        - name: rocketmq.config.namesrvAddr
          value: {{ .Values.rocketmqBrokerA.nameServerAddr | quote }}
        - name: rocketmq.config.rocketmqVersion
          value: {{ .Values.rocketmqExporter.rocketmqVersion | quote }}
        - name: rocketmq.config.enableACL
          value: "false"
 #       - name: rocketmq.config.accessKey
 #         value: rocketmq2
 #       - name: rocketmq.config.secretKey
 #         value: ymsl@2021
        image: {{ .Values.rocketmqExporter.image }}:{{ .Values.rocketmqExporter.tag }}
        imagePullPolicy: IfNotPresent
        name: {{ .Values.rocketmqExporter.name }}
        ports:
        - containerPort: 5557
          protocol: TCP
        resources:
{{- with .Values.rocketmqExporter.resources }}
{{ toYaml . | indent 10 }}
{{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
{{- end }}
