---
rocketmqOperator:
  name: rocketmq-operator
  operatorImageName: aosolao/rocketmq-operator
  operatorImageTag: 0.3.0
  imagePullPolicy: IfNotPresent
  terminationGracePeriodSeconds: 10
  # Additional pod annotations
  podAnnotations: {}
  # Additional Pod labels (e.g. for filtering Pod by custom labels)
  podLabels: {}
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  replicas: 1
  serviceAccountName: rocketmq-operator
  priorityClassName: ""
  nodeSelector: {}
  tolerateAllTaints: false
  tolerations: []
  affinity: {}

ConfigMap:
  name: broker-config
  # BROKER_MEM sets the broker JVM, if set to "" then Xms :  Xmx :  max(min(1/2 ram, 1024MB), min(1/4 ram, 8GB))
  BROKER_MEM: " -Xms1g -Xmx1g -Xmn512m "
  # brokerClusterName, brokerName, brokerId 会自动填充，不要手动修改!!!
  broker_conf:
    # 删除文件时间点，默认凌晨 4点
    deleteWhen: 04
    # 文件保留时间，默认 48 小时
    fileReservedTime: 72
    #- ASYNC_FLUSH 异步刷盘
    #- SYNC_FLUSH 同步刷盘
    flushDiskType: ASYNC_FLUSH
    # set brokerRole to ASYNC_MASTER or SYNC_MASTER. DO NOT set to SLAVE because the replica instance will automatically be set!!!
    brokerRole: ASYNC_MASTER
    # ACL开关
    aclEnable: true
    # 从节点可读
    slaveReadEnable: true
    #在发送消息时，自动创建服务器不存在的topic，默认创建的队列数
    defaultTopicQueueNums: 4
    #是否允许 Broker 自动创建Topic，建议线下开启，线上关闭
    autoCreateTopicEnable: false
    #是否允许 Broker 自动创建订阅组，建议线下开启，线上关闭
    autoCreateSubscriptionGroup: false
    #commitLog每个文件的大小默认1G
    mapedFileSizeCommitLog: 1073741824
    #ConsumeQueue每个文件默认存30W条，根据业务情况调整
    mapedFileSizeConsumeQueue: 300000
    #检测物理文件磁盘空间
    diskMaxUsedSpaceRatio: 88
    #限制的消息大小
    maxMessageSize: 4194304
    #发消息线程池数量
    #sendMessageThreadPoolNums: 128
    #拉消息线程池数量
    #pullMessageThreadPoolNums: 128
  plain_acl_yml:
    globalWhiteRemoteAddresses:
      - 10.*.*.*
    accounts:
      #- accessKey: RocketMQ
      #  secretKey: 12345678
      #  whiteRemoteAddress:
      #  admin: false
      #  defaultTopicPerm: DENY
      #  defaultGroupPerm: SUB
      #  topicPerms:
      #    - topicA: DENY
      #    - topicB: PUB|SUB
      #    - topicC: SUB
      #  groupPerms:
          # the group should convert to retry topic
      #    - groupA: DENY
      #    - groupB: PUB|SUB
      #    - groupC: SUB
      - accessKey: rocketmq2
        secretKey: 12345678oo
        whiteRemoteAddress:
        # if it is admin, it could access all resources
        admin: true
  tools_yml:
    accessKey: rocketmq2
    secretKey: 12345678oo

rocketmqNameserver:
  name: name-service
  nameserverImageName: aosolao/rocketmq-nameserver
  nameserverImageTag: 4.9.4-alpine-operator-0.3.0
  # size is the the name service instance number of the name service cluster
  size: 1
  # imagePullPolicy is the image pull policy
  imagePullPolicy: IfNotPresent
  # hostNetwork can be true or false
  hostNetwork: false
  #  Set DNS policy for the pod.
  #  Defaults to "ClusterFirst".
  #  Valid values are 'ClusterFirstWithHostNet', 'ClusterFirst', 'Default' or 'None'.
  #  DNS parameters given in DNSConfig will be merged with the policy selected with DNSPolicy.
  #  To have DNS options set along with hostNetwork, you have to specify DNS policy
  #  explicitly to 'ClusterFirstWithHostNet'.
  dnsPolicy: ClusterFirst
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1024Mi"
      cpu: "500m"
  # storageMode can be EmptyDir, HostPath, StorageClass
  storageMode: EmptyDir
  # hostPath is the local path to store data
  hostPath: /data/rocketmq/broker
  volumeClaimTemplates:
    - metadata:
        name: namesrv-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local
        resources:
          requests:
            storage: 1Gi
  networkType: ClusterIP
  clusterPort: 9876
  # 如果不使用nodePort方式，则注释该项目
  #nodePort: 30001

rocketmqBroker:
  name: broker
  # size is the number of the broker cluster, each broker cluster contains a master broker and [replicaPerGroup] replica brokers.
  size: 1
  # replicaPerGroup is the number of each broker cluster
  replicaPerGroup: 1
  brokerImageName:  aosolao/rocketmq-broker
  brokerImageTag: 4.9.4-alpine-operator-0.3.0-with-acl-1026
  # imagePullPolicy is the image pull policy
  imagePullPolicy: IfNotPresent
  # resources describes the compute resource requirements and limits
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "2048Mi"
  # allowRestart defines whether allow pod restart
  allowRestart: true
  # storageMode can be EmptyDir, HostPath, StorageClass
  storageMode: StorageClass
  # hostPath is the local path to store data
  hostPath: /data/rocketmq/broker
  # scalePodName is [Broker name]-[broker group number]-master-0
  scalePodName: broker-0-master-0
  # volumeClaimTemplates defines the storageClass
  volumeClaimTemplates:
    - metadata:
        name: broker-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local
        resources:
          requests:
            storage: 1Gi

rocketmqConsole:
  name: console
  progressDeadlineSeconds: 600
  consoleImageName: aosolao/rocketmq-console
  consoleImageTag: v3
  replicas: 1
  imagePullPolicy: IfNotPresent
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  javaOpts: "-Drocketmq.namesrv.addr:name-service:9876 -Dcom.rocketmq.sendMessageWithVIPChannel:false -Drocketmq.config.accessKey:rocketmq2 -Drocketmq.config.secretKey:12345678oo"
  networkType: NodePort
  containerPort: 8080
  # 如果不使用nodePort方式，则注释该项目
  nodePort: 30000
  clusterPort: 8080
