---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}  
  template:
    metadata:
      labels:
        app: event-exporter
        version: v1
      annotations:
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ .Release.Name }}
          # The good practice would be to pin the version. This is just a reference so that we don't
          # have to update this file in each release.
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          args:
            - -conf=/data/config.yaml
          volumeMounts:
            - mountPath: /data
              name: cfg
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}
      volumes:
        - name: cfg
          configMap:
            name: {{ .Release.Name }}-cfg
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
  selector:
    matchLabels:
      app: event-exporter
      version: v1

